In [9]:
import numpy as np
import pandas as pd

import os
dir= os.getcwd()
path = os.path.join(dir, "play_tennis.csv")

In [10]:
data = pd.read_csv(path)
data.drop(columns=['day'], inplace=True)
data.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [11]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

# problem 1 

# outlook = sunny, temp = hot, humidity = high , wind = weak

# play or No play?

solution 

p (yes | sunny, hot, high , weak) = p(sunny | yes) * p(hot|yes) * p(high | yes) * p(weak|yes)*p(yes)

p(No | sunny, hot, high , weak) = p(sunny|NO)* p(hot|No)* p(high|No)* p(weak|No)*p(No)

compare and decide using the maximum a posteriori rule

In [ ]:
# Training

# Lookup Table (dictionary)

# Testing

In [13]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [15]:
py = 9/14
pn = 5/14

In [16]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [17]:
# outlook

pd.crosstab(data['outlook'], data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [23]:
POvercastNo = 0
PrainNo = 2/5
PSunnyNo = 3/5

POvercastYes = 4/9
PRainYes = 3/9
PSunnyYes = 2/9

In [19]:
# temp
pd.crosstab(data['temp'], data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [24]:
PCoolNo = 1/5
PHotNo= 2/5
PMildNo = 2/5

PCollYes= 3/9
PHotYes = 2/9
PMildYes = 4/9

In [21]:
# humidity
pd.crosstab(data['humidity'], data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [25]:
PHighNo = 4/5
PNormalNo = 1/5

PHighYes= 3/9
PNormalYes= 6/9

In [26]:
# wind
pd.crosstab(data['wind'], data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [27]:
PStrongNo = 3/5
PWeakNo = 2/5

PStrongYes = 3/9
PWeakYes = 6/9

In [29]:
# outlook = sunny, temp = hot, humidity = high , wind = weak

Pyes = py*PSunnyYes*PHotYes*PHighYes*PWeakYes

PNo = pn*PSunnyNo*PHotNo*PHighNo*PWeakNo

In [30]:
print(Pyes, PNo)

0.007054673721340388 0.02742857142857143

In [ ]:
# No play - conclusion